In [12]:
import numpy as np

In [ ]:
# arreglo de 1 dimensión
arr1 = np.array([1, 2, 3])

In [15]:
type(arr1)

numpy.ndarray

In [17]:
arr1 + 1

array([2, 3, 4])

In [ ]:
arr1 = np.array(
    [
        [1, 2, 3],
        [2, 4, 8]
    ]
)
arr1

array([[1, 2, 3],
       [2, 4, 8]])

In [ ]:

arr1.shape

(2, 3)

In [ ]:
# int64 -> 0101010011
int

int

In [28]:
np.ones(shape=(5,2), dtype=np.int32)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [ ]:
#-127,128
2**8, 2**16, 2**32, 2**64

(256, 65536, 4294967296, 18446744073709551616)

In [46]:
ones_array = np.ones(shape=(5, 2), dtype=np.int8)
ones_array*200

array([[200, 200],
       [200, 200],
       [200, 200],
       [200, 200],
       [200, 200]], dtype=int16)

In [34]:
np.zeros(shape=(5, 2), dtype=np.float16)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float16)

In [47]:
np.random.random(size=(5, 2))

array([[0.74004667, 0.68257866],
       [0.41047937, 0.31145971],
       [0.0670165 , 0.59332855],
       [0.70444526, 0.59188211],
       [0.72272707, 0.38343075]])

In [55]:
array1= np.ones(shape=(5, 2)) * 12
array2 = np.ones(shape=(5, 3)) * 3


In [56]:
array1

array([[12., 12.],
       [12., 12.],
       [12., 12.],
       [12., 12.],
       [12., 12.]])

In [57]:
array2

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [58]:
array1 + array2

ValueError: operands could not be broadcast together with shapes (5,2) (5,3) 

In [59]:
array1 = np.ones(shape=(5, 2)) * 12
array2 = np.ones(shape=(5, 2)) * 3

In [60]:
array1 + array2

array([[15., 15.],
       [15., 15.],
       [15., 15.],
       [15., 15.],
       [15., 15.]])

In [61]:
array1 / array2

array([[4., 4.],
       [4., 4.],
       [4., 4.],
       [4., 4.],
       [4., 4.]])

In [62]:
array1 * array2

array([[36., 36.],
       [36., 36.],
       [36., 36.],
       [36., 36.],
       [36., 36.]])

In [ ]:
array1 ** array2 

array([[1728., 1728.],
       [1728., 1728.],
       [1728., 1728.],
       [1728., 1728.],
       [1728., 1728.]])

In [65]:
array2 * 1

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [75]:
array3 = np.arange(10).reshape(5, 2)
array3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [79]:
array3[0]

array([0, 1])

In [ ]:
array3[4, 1]

9

In [80]:
array3[:,1]

array([1, 3, 5, 7, 9])

In [ ]:
array3[:2, 1]

array([1, 3])

In [ ]:
array3[:2, :2]

array([[0, 1],
       [2, 3]])

In [ ]:
array3[0,0] =100
array3

array([[100,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9]])

In [85]:
array3[1:, 1] = 12
array3

array([[100,   1],
       [  2,  12],
       [  4,  12],
       [  6,  12],
       [  8,  12]])

In [110]:
array4 = np.random.random(size=(5, 2))
mask = array4 > 0.5
mask

array([[False,  True],
       [ True,  True],
       [False, False],
       [False,  True],
       [ True, False]])

In [111]:
array4[mask] = 0

In [112]:
array4

array([[0.00752604, 0.        ],
       [0.        , 0.        ],
       [0.13363948, 0.28859676],
       [0.0888724 , 0.        ],
       [0.        , 0.34971502]])

In [113]:
array4[0,1] = 1
array4[4, 1] = 1

In [114]:
array4

array([[0.00752604, 1.        ],
       [0.        , 0.        ],
       [0.13363948, 0.28859676],
       [0.0888724 , 0.        ],
       [0.        , 1.        ]])

In [115]:
# [[filas], [columnas]]
array4[[0,4], [1,1]] = -1
array4

array([[ 0.00752604, -1.        ],
       [ 0.        ,  0.        ],
       [ 0.13363948,  0.28859676],
       [ 0.0888724 ,  0.        ],
       [ 0.        , -1.        ]])

In [103]:
array5 = np.random.random(size=(5, 2))
array6 = np.zeros(shape=(5, 3))

In [106]:
array6[:,:2] = array5 

In [107]:
array6

array([[0.01015784, 0.76203233, 0.        ],
       [0.42221423, 0.78291028, 0.        ],
       [0.42858518, 0.31939186, 0.        ],
       [0.7542973 , 0.39601416, 0.        ],
       [0.66712538, 0.64698181, 0.        ]])

In [118]:
notas = np.random.randint(low=0, high=100, size=(21, 5))
notas

array([[12, 24, 62, 48, 18],
       [34, 33, 32, 91, 14],
       [71, 46,  9, 18, 90],
       [47, 44, 13, 49,  0],
       [32, 66, 88, 97, 96],
       [55, 97, 50, 94, 97],
       [69, 51, 51, 25, 43],
       [19, 40, 21,  7, 13],
       [36, 57,  2, 15, 13],
       [85, 89, 20,  7, 44],
       [40, 95, 65, 95, 62],
       [ 2, 85, 68, 38, 34],
       [19, 38, 90, 64, 81],
       [78, 29, 61, 94, 48],
       [22, 58, 18, 48, 89],
       [93,  2, 77, 73, 28],
       [83, 94, 15, 24,  5],
       [50, 35, 13, 62, 73],
       [35,  2, 84, 70,  9],
       [84, 86, 10, 28, 46],
       [19, 27, 93, 12, 37]])

In [119]:
notas.max()

97

In [ ]:
notas.argmax(axis=0)

array([15,  5, 20,  4,  5])

In [126]:
notas.argmax(axis=1)

array([2, 3, 4, 3, 3, 1, 0, 1, 1, 1, 1, 1, 2, 3, 4, 0, 1, 4, 2, 1, 2])

In [121]:
notas.mean()

47.84761904761905

In [129]:
mean_by_exam = notas.mean(axis=0)
mean_by_exam

array([46.9047619 , 52.28571429, 44.85714286, 50.42857143, 44.76190476])

In [128]:
notas.mean(axis=1)

array([32.8, 40.8, 46.8, 30.6, 75.8, 78.6, 47.8, 20. , 24.6, 49. , 71.4,
       45.4, 58.4, 62. , 47. , 54.6, 44.2, 46.6, 40. , 50.8, 37.6])

In [133]:
notas - mean_by_exam.astype(np.int32)

array([[-34, -28,  18,  -2, -26],
       [-12, -19, -12,  41, -30],
       [ 25,  -6, -35, -32,  46],
       [  1,  -8, -31,  -1, -44],
       [-14,  14,  44,  47,  52],
       [  9,  45,   6,  44,  53],
       [ 23,  -1,   7, -25,  -1],
       [-27, -12, -23, -43, -31],
       [-10,   5, -42, -35, -31],
       [ 39,  37, -24, -43,   0],
       [ -6,  43,  21,  45,  18],
       [-44,  33,  24, -12, -10],
       [-27, -14,  46,  14,  37],
       [ 32, -23,  17,  44,   4],
       [-24,   6, -26,  -2,  45],
       [ 47, -50,  33,  23, -16],
       [ 37,  42, -29, -26, -39],
       [  4, -17, -31,  12,  29],
       [-11, -50,  40,  20, -35],
       [ 38,  34, -34, -22,   2],
       [-27, -25,  49, -38,  -7]])

In [134]:
notas - mean_by_exam.round(2)

array([[-34.9 , -28.29,  17.14,  -2.43, -26.76],
       [-12.9 , -19.29, -12.86,  40.57, -30.76],
       [ 24.1 ,  -6.29, -35.86, -32.43,  45.24],
       [  0.1 ,  -8.29, -31.86,  -1.43, -44.76],
       [-14.9 ,  13.71,  43.14,  46.57,  51.24],
       [  8.1 ,  44.71,   5.14,  43.57,  52.24],
       [ 22.1 ,  -1.29,   6.14, -25.43,  -1.76],
       [-27.9 , -12.29, -23.86, -43.43, -31.76],
       [-10.9 ,   4.71, -42.86, -35.43, -31.76],
       [ 38.1 ,  36.71, -24.86, -43.43,  -0.76],
       [ -6.9 ,  42.71,  20.14,  44.57,  17.24],
       [-44.9 ,  32.71,  23.14, -12.43, -10.76],
       [-27.9 , -14.29,  45.14,  13.57,  36.24],
       [ 31.1 , -23.29,  16.14,  43.57,   3.24],
       [-24.9 ,   5.71, -26.86,  -2.43,  44.24],
       [ 46.1 , -50.29,  32.14,  22.57, -16.76],
       [ 36.1 ,  41.71, -29.86, -26.43, -39.76],
       [  3.1 , -17.29, -31.86,  11.57,  28.24],
       [-11.9 , -50.29,  39.14,  19.57, -35.76],
       [ 37.1 ,  33.71, -34.86, -22.43,   1.24],
       [-27.9 , -25.

In [136]:
notas1 = np.random.randint(low=0, high=100, size=(3, 2))
notas1

array([[89, 56],
       [20, 62],
       [84, 70]])

In [140]:
notas1 @ notas1.T

array([[11057,  5252, 11396],
       [ 5252,  4244,  6020],
       [11396,  6020, 11956]])

In [142]:
notas1.shape, notas1.T.shape

((3, 2), (2, 3))